application: diploma
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png

- url: /
  script: handlers.main.app

- url: /doComment
  script: handlers.doComment.app

- url: /video
  script: handlers.video.app

- url: /static
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
